name: Stamp API Actions
on: 
  pull_request:
    branches:
      - main
jobs:
  Set-Up-JDK:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          
      - name: Set up Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '16'
          postgresql db: 'testdb'
          postgresql user: 'testuser'
          postgresql password: 'testpass'

      - name: Set environment variables
        run: |
          echo "DB_URL=jdbc:postgresql://localhost:5432/testdb" >> $GITHUB_ENV
          echo "DB_USER=testuser" >> $GITHUB_ENV
          echo "DB_PASSWORD=testpass" >> $GITHUB_ENV
      - name: Build with Maven
        run: |
          ./mvnw clean install
        env:
          DB_URL: ${{ env.DB_URL }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          
          
          
      
  
