name: Stamp API Actions
on: 
  pull_request:
    branches:
      - main
jobs:
  Set-Up-JDK:
    runs-on: ubuntu-latest
    # set up a postgres server to connect to
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Maven
        run: |
          mvn -B package --file pom.xml
          
          
      
  
